"""Reproduce all 14 supplementary figures (S1 – S14).

S1 – S9 + S13 are per-dataset 12-method views generated by
    `generators/plot_improved.py::make_supp_per_dataset(dataset_key)`

S10 (sensitivity), S11 (runtime + memory) and S12 (extended ablation) are
generated by `generators/experiments/plot_supp_figures.py`:
    plot_supp_fig_S7  → FigS10_sensitivity      (parameter sensitivity)
    plot_supp_fig_S8  → FigS11_runtime          (runtime + memory)
    plot_supp_fig_S6  → FigS12_ext_ablation     (extended ablation)

S14 (scIB-aggregation robustness, P0-2) is generated by
    `generators/phase2_scib_robustness_fig.py::main()`  → FigS14_scIB_robustness
"""

from __future__ import annotations
from pathlib import Path

from _common import attach_resource_root

RESOURCE_ROOT: Path | None = None
attach_resource_root(RESOURCE_ROOT)

import plot_improved as P                  # noqa: E402
import plot_supp_figures as PSF            # noqa: E402
import phase2_scib_robustness_fig as PSR   # noqa: E402


# (dataset key, supp figure id) — must match SUPPL_PER_DATASET in plot_improved.py
PER_DATASET = [
    ("data1_scenario1",  "S1"),
    ("data1_scenario2",  "S2"),
    ("data2_scenario1",  "S3"),
    ("data2_scenario2",  "S4"),
    ("Sc_mixology",      "S5"),
    ("PBMC",             "S6"),
    ("Human_Pancreas",   "S7"),
    ("Immune_human",     "S8"),
    ("gut",              "S9"),
    ("Lung",             "S13"),
]


if __name__ == "__main__":
    # S1 – S9, S13 — per-dataset 12-method views
    for ds, supp_id in PER_DATASET:
        try:
            print(f"\n=== Suppl Fig {supp_id} — dataset {ds} ===")
            P.make_supp_per_dataset(ds)
        except Exception as exc:
            print(f"  [ERROR] {supp_id} failed: {exc}")

    # S10 — parameter sensitivity
    try:
        print("\n=== Suppl Fig S10 — sensitivity ===")
        PSF.plot_supp_fig_S7()
    except Exception as exc:
        print(f"  [ERROR] S10 failed: {exc}")

    # S11 — runtime + memory
    try:
        print("\n=== Suppl Fig S11 — runtime ===")
        PSF.plot_supp_fig_S8()
    except Exception as exc:
        print(f"  [ERROR] S11 failed: {exc}")

    # S12 — extended ablation
    try:
        print("\n=== Suppl Fig S12 — extended ablation ===")
        PSF.plot_supp_fig_S6()
    except Exception as exc:
        print(f"  [ERROR] S12 failed: {exc}")

    # S14 — scIB-aggregation robustness (P0-2)
    try:
        print("\n=== Suppl Fig S14 — scIB-aggregation robustness ===")
        PSR.main()
    except Exception as exc:
        print(f"  [ERROR] S14 failed: {exc}")

    print("\nAll supplementary figures written under generators/figures/")
